import React from 'react'
import Head from 'next/head'

import AboutLayout from '../../Layouts/AboutMeLayout/AboutLayout'

const Hobbies = () => {
  return (
    <div>
      <Head>
        <title>Joseph Enoch | About Me | Hobbies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      hobbies</div>
  )
}

Hobbies.Layout = AboutLayout

export default Hobbies