import React from 'react'
import AboutLayout from '../../Layouts/AboutMeLayout/AboutLayout'
import Head from 'next/head'

const professionalInfo = () => {
  return (
    <div>
      <Head>
        <title>Joseph Enoch | About Me | Professional Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Professional Info
    </div>
  )
}

professionalInfo.Layout = AboutLayout

export default professionalInfo